### ISSUE TITLE
Need to xml file urlset

### ISSUE THREAD

**Issue by pprignesh** [magefan/module-blog-sitemap#6]
hello,

i need to change urlsel from xml file from 
`<urlset xmlns="http://www.blogsitemaps.org/schemas/blogsitemap/0.9" xmlns:image="http://www.google.com/schemas/blogsitemap-image/1.1">`
to
`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
`
How can we do it?

Thanks

**Comment by magefan** [comment]
@pprignesh , thank you for your request.

This issue was already fixed by this commit https://github.com/magefan/module-blog-sitemap/commit/a723d15b0dcd8e94e38584acff89cbcc22cbc23a 3 month ago.

All you need to do is update [magefan/module-blog-sitemap](https://github.com/magefan/module-blog-sitemap) package for the [Magento 2 Blog Module](https://magefan.com/magento2-blog-extension) to the latest version. The current latest version is [2.0.3](https://github.com/magefan/module-blog-sitemap/releases/tag/2.0.3).
